
version: '3.3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/data/portainer:/data
  # em construção
  samba4:
    container_name: samba4
    build:
      context: .
      dockerfile: ./docker/samba4-ad-dc/Dockerfile
    ports: 
      - "1111:1111"
    volumes:
      - ${PWD}/samba:/var/lib/samba
      - ${PWD}/samba:/etc/samba
    environment: 
        - SAMBA_REALM="example.org"
        - SAMBA_DOMAIN="example"
        - ROOT_PASSWORD="adminpassword"
        - SAMBA_ADMIN_PASSWORD="adminpassword"
        - SAMBA_DNS_FORWARDER="8.8.8.8" 
    ports:
        - 53:53
        - 53:53/udp
        - 88:88
        - 88:88/udp
        - 135:135
        - 139:139
        - 389:389
        - 389:389/udp
        
    networks: 
      - lab-net

  openldap:
    container_name: openldap
    image: docker.io/bitnami/openldap:2.5
    ports:
      - '1389:1389'
      # - '1636:1636'  
    volumes:
      - './docker/data/openldap:/bitnami/openldap'
    environment: 
      - LDAP_ROOT=DC=example,DC=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks: 
      - lab-net

  ldap-backend:
    depends_on: 
      - openldap
    container_name: ldap-backend
    build:
      context: .
      dockerfile: ./ldap-backend.Dockerfile
    command: npm start
    ports: 
      - "1111:1111"
    volumes:
      - ./:/usr/app
    networks: 
      - lab-net

networks: 
  lab-net:
      driver: bridge
